/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.1.1.232.1
    Soft IP Version: 1.5.0.00
    2022 04 04 20:32:16
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module tx_dphy_s (ref_clk_i, reset_n_i, pd_dphy_i, byte_or_pkt_data_i,
    byte_or_pkt_data_en_i, ready_o, vc_i, dt_i, wc_i, clk_hs_en_i, d_hs_en_i,
    tinit_done_o, pll_lock_o, pix2byte_rstn_o, pkt_format_ready_o, d_hs_rdy_o,
    byte_clk_o, c2d_ready_o, phdr_xfr_done_o, ld_pyld_o, clk_p_io, clk_n_io,
    d_p_io, d_n_io, pll_clkop_i, pll_lock_i, sp_en_i, lp_en_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  reset_n_i;
    input  pd_dphy_i;
    input  [7:0]  byte_or_pkt_data_i;
    input  byte_or_pkt_data_en_i;
    output  ready_o;
    input  [1:0]  vc_i;
    input  [5:0]  dt_i;
    input  [15:0]  wc_i;
    input  clk_hs_en_i;
    input  d_hs_en_i;
    output  tinit_done_o;
    output  pll_lock_o;
    output  pix2byte_rstn_o;
    output  pkt_format_ready_o;
    output  d_hs_rdy_o;
    output  byte_clk_o;
    output  c2d_ready_o;
    output  phdr_xfr_done_o;
    output  ld_pyld_o;
    inout  clk_p_io;
    inout  clk_n_io;
    inout  [0:0]  d_p_io;
    inout  [0:0]  d_n_io;
    input  pll_clkop_i;
    input  pll_lock_i;
    input  sp_en_i;
    input  lp_en_i;
endmodule