/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.2.0.38.1
    Soft IP Version: 1.8.0
    2024 03 17 12:20:48
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module main_pll (clki_i, rstn_i, clkop_o, clkos_o, clkos2_o, clkos3_o,
    clkos4_o, clkos5_o, lock_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    input  rstn_i;
    output  clkop_o;
    output  clkos_o;
    output  clkos2_o;
    output  clkos3_o;
    output  clkos4_o;
    output  clkos5_o;
    output  lock_o;
endmodule