/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.1.1.232.1
    Soft IP Version: 1.3.0
    2022 04 07 17:52:17
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module B2P (reset_byte_n_i, clk_byte_i, sp_en_i, dt_i, lp_av_en_i,
    payload_en_i, payload_i, wc_i, reset_pixel_n_i, clk_pixel_i, fv_o, lv_o,
    pd_o, p_odd_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  reset_byte_n_i;
    input  clk_byte_i;
    input  sp_en_i;
    input  [5:0]  dt_i;
    input  lp_av_en_i;
    input  payload_en_i;
    input  [7:0]  payload_i;
    input  [15:0]  wc_i;
    input  reset_pixel_n_i;
    input  clk_pixel_i;
    output  fv_o;
    output  lv_o;
    output  [9:0]  pd_o;
    output  [1:0]  p_odd_o;
endmodule