    B2P u_B2P(.reset_byte_n_i(reset_byte_n_i),
        .clk_byte_i(clk_byte_i),
        .sp_en_i(sp_en_i),
        .dt_i(dt_i),
        .lp_av_en_i(lp_av_en_i),
        .payload_en_i(payload_en_i),
        .payload_i(payload_i),
        .wc_i(wc_i),
        .reset_pixel_n_i(reset_pixel_n_i),
        .clk_pixel_i(clk_pixel_i),
        .fv_o(fv_o),
        .lv_o(lv_o),
        .pd_o(pd_o),
        .p_odd_o(p_odd_o));
